# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQ2Iq-O4CJaPHA9X-ZL-KQyMCc-p5aet
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files
uploaded = files.upload()

data = np.genfromtxt("jan - Sheet1.csv", delimiter=",", names=["x", "y"])

plt.plot(data['x'], data['y'])
plt.xlabel("hour (h)")
plt.ylabel("insolation (kW/m²)")

!pip install area_under_curve

x = data["x"]
y = data["y"]
z = np.polyfit(x, y, 2)

z

b = 4

def func(x):
    return -0.03968778*(x**2)+0.86343964*x-3.73320542

from scipy.integrate import simps
from numpy import trapz

areatrap = trapz(y, x)

areatrap

areasimp = simps(y, x*x)

areasimp

a = 2
b = a^2

print(b)

from google.colab import files
uploaded = files.upload()

